# Generated by Django 3.0.3 on 2020-02-25 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=20)),
                ('given_name', models.CharField(max_length=20)),
                ('family_name_huri', models.CharField(max_length=50)),
                ('given_name_huri', models.CharField(max_length=50)),
                ('birth', models.CharField(max_length=10)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('address', models.CharField(max_length=50)),
                ('career', models.TextField(blank=True)),
                ('firstyear_class', models.IntegerField(blank=True, null=True)),
                ('firstyear_number', models.IntegerField(blank=True, null=True)),
                ('secondyear_class', models.IntegerField(blank=True, null=True)),
                ('secondyear_number', models.IntegerField(blank=True, null=True)),
                ('thirdyear_class', models.IntegerField(blank=True, null=True)),
                ('thirdyear_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_out', models.DateField()),
                ('after_out', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entrance', models.DateField()),
                ('grade_entrance', models.IntegerField()),
                ('before_entrance', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=20)),
                ('parent_name_huri', models.CharField(max_length=50)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_graduation', models.DateField()),
                ('after_graduation', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
    ]
