# Generated by Django 3.0.3 on 2020-02-25 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200225_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='parent_name',
            new_name='parent_family_name',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='parent_name_huri',
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_family_name_huri',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_given_name',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_given_name_huri',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
